Repository teamsindy20/sobok-backend, pull requests merged in 2021-09, with the labels that each got.

#38 Feature/#34/optimize menu query
  .github/workflows/apollo-graphql-dev.yml
  .github/workflows/apollo-graphql.yml
  .github/workflows/codeql-analysis.yml
  codegen.yml
  package.json
  src/apollo/server.ts
  src/graphql/feed/ORM.ts
  src/graphql/feed/Query.graphql
  src/graphql/feed/Query.resolver.ts
  src/graphql/feed/sql/byId.sql
  src/graphql/feed/sql/joinHashtag.sql
  src/graphql/feed/sql/joinLikedStore.sql
  src/graphql/generated/graphql.ts
  src/graphql/generated/schema.graphql
  src/graphql/menu/ORM.ts
  src/graphql/menu/Object.resolver.ts
  src/graphql/menu/Query.graphql
  src/graphql/menu/Query.resolver.ts
  src/graphql/menu/sql/byCategory.sql
  src/graphql/menu/sql/byId.sql
  src/graphql/menu/sql/byName.sql
  src/graphql/menu/sql/byStoreId.sql
  src/graphql/menu/sql/hashtags.sql
  src/graphql/menu/sql/isLiked.sql
  src/graphql/menu/sql/joinHashtag.sql
  src/graphql/menu/sql/joinLikedMenu.sql
  src/graphql/menu/sql/joinMenuBucket.sql
  src/graphql/menu/sql/joinStore.sql
  src/graphql/menu/sql/joinStoreOnTown.sql
  src/graphql/menu/sql/joinStoreOnTownAndCategory.sql
  src/graphql/menu/sql/menu.sql
  src/graphql/menu/sql/menuByName.sql
  src/graphql/menu/sql/menus.sql
  src/graphql/menu/sql/menusByCategory.sql
  src/graphql/menu/sql/menusByStoreId.sql
  src/graphql/menu/sql/menusByTown.sql
  src/graphql/menu/sql/menusByTownAndCategory.sql
  src/graphql/menu/sql/store.sql
  src/graphql/news/ORM.ts
  src/graphql/news/Object.resolver.ts
  src/graphql/news/Query.graphql
  src/graphql/news/Query.resolver.ts
  src/graphql/news/sql/joinStoreOnTown.sql
  src/graphql/schema.ts
  src/graphql/store/ORM.ts
  src/graphql/user/Mutation.graphql
  src/graphql/user/Object.resolver.ts
  src/utils/ORM.ts
  yarn.lock
Labels: ⚒ refactor

#41 Fix/#40/store menu feed news api maintainance
  .github/workflows/apollo-graphql-dev.yml
  .github/workflows/apollo-graphql.yml
  src/graphql/feed/ORM.ts
  src/graphql/feed/Query.resolver.ts
  src/graphql/feed/sql/joinHashtag.sql
  src/graphql/generated/graphql.ts
  src/graphql/generated/schema.graphql
  src/graphql/menu/ORM.ts
  src/graphql/menu/Object.resolver.ts
  src/graphql/menu/Query.resolver.ts
  src/graphql/menu/sql/joinMenuBucket.sql
  src/graphql/news/ORM.ts
  src/graphql/store/ORM.ts
  src/graphql/store/Object.resolver.ts
  src/graphql/store/Query.graphql
  src/graphql/store/Query.resolver.ts
  src/graphql/store/sql/byCategories.sql
  src/graphql/store/sql/byId.sql
  src/graphql/store/sql/byTown.sql
  src/graphql/store/sql/byTownAndCategories.sql
  src/graphql/store/sql/joinHashtag.sql
  src/graphql/store/sql/joinLikedStore.sql
  src/graphql/store/sql/joinMenu.sql
  src/graphql/store/sql/joinNews.sql
  src/graphql/store/sql/joinStoreBucket.sql
  src/graphql/store/sql/joinUser.sql
  src/graphql/store/sql/stores.sql
  src/graphql/store/sql/storesByCategories.sql
  src/graphql/store/sql/storesByTown.sql
  src/graphql/store/sql/storesByTownAndCategories.sql
  src/graphql/user/ORM.ts
  src/graphql/user/Object.graphql
  src/graphql/user/Object.resolver.ts
  src/utils/ORM.ts
Labels: bug, ⚒ refactor

#45 Feature/#42/bucket api
  database/sql/initialization.sql
  database/sql/procedures.sql
  src/graphql/bucket/ORM.ts
  src/graphql/bucket/Object.graphql
  src/graphql/bucket/Object.resolver.ts
  src/graphql/bucket/Query.graphql
  src/graphql/bucket/Query.resolver.ts
  src/graphql/bucket/sql/byId.sql
  src/graphql/bucket/sql/byUserIdAndMenuBucket.sql
  src/graphql/bucket/sql/byUserIdAndStoreBucket.sql
  src/graphql/bucket/sql/fromBucket.sql
  src/graphql/bucket/sql/joinUser.sql
  src/graphql/feed/ORM.ts
  src/graphql/generated/graphql.ts
  src/graphql/generated/schema.graphql
  src/graphql/menu/Object.resolver.ts
  src/graphql/menu/Query.graphql
  src/graphql/menu/Query.resolver.ts
  src/graphql/menu/sql/byMenuBucketId.sql
  src/graphql/menu/sql/joinMenuBucketOnMenuBucketId.sql
  src/graphql/news/Query.graphql
  src/graphql/news/Query.resolver.ts
  src/graphql/news/sql/byCategories.sql
  src/graphql/news/sql/onTown.sql
  src/graphql/store/Query.graphql
  src/graphql/store/Query.resolver.ts
  src/graphql/store/sql/byStoreBucketId.sql
  src/graphql/store/sql/joinStoreBucketOnStoreBucketId.sql
  src/graphql/trend/Object.graphql
  src/graphql/user/ORM.ts
  src/graphql/user/Object.graphql
  src/graphql/user/Object.resolver.ts
  src/graphql/user/Query.graphql
  src/graphql/user/Query.resolver.ts
  src/graphql/user/sql/fromUser.sql
  src/graphql/user/sql/joinComment.sql
  src/graphql/user/sql/joinFeed.sql
  src/graphql/user/sql/joinLeaderFollower.sql
Labels: ⚒ refactor

#49 Fix/#48/login security issue
  .vscode/typescript.code-snippets
  database/sql/initialization.sql
  package.json
  src/apollo/server.ts
  src/common/passport.ts
  src/database/sobok.ts
  src/graphql/user/Mutation.resolver.ts
  src/utils/commons.ts
  yarn.lock
Labels: bug

#51 Fix/#48/login security issue
  database/sql/initialization.sql
  database/sql/procedures.sql
  src/apollo/server.ts
  src/database/sobok.ts
  src/graphql/generated/graphql.ts
  src/graphql/generated/schema.graphql
  src/graphql/user/Mutation.graphql
  src/graphql/user/Mutation.resolver.ts
  src/graphql/user/ORM.ts
  src/graphql/user/Query.graphql
  src/graphql/user/Query.resolver.ts
  src/graphql/user/sql/byId.sql
  src/graphql/user/sql/joinFollower.sql
  src/graphql/user/sql/joinFollowing.sql
  src/graphql/user/sql/login.sql
  src/graphql/user/sql/register.sql
Labels: ⚒ refactor

#52 Update packages
  .eslintrc.json
  package.json
  src/graphql/generated/graphql.ts
  yarn.lock
Labels: ⚒ refactor

#55 Feature/#54/store latitude longitude
  database/sql/initialization.sql
  database/sql/procedures.sql
  src/database/sobok.ts
  src/graphql/common/scalar.graphql
  src/graphql/common/scalar.resolver.ts
  src/graphql/generated/graphql.ts
  src/graphql/generated/schema.graphql
  src/graphql/store/ORM.ts
  src/graphql/store/Object.graphql
Labels: ☁️ new feature

#50 Develop
  .eslintrc.json
  .vscode/typescript.code-snippets
  database/sql/initialization.sql
  database/sql/procedures.sql
  package.json
  src/apollo/server.ts
  src/common/passport.ts
  src/database/sobok.ts
  src/graphql/common/scalar.graphql
  src/graphql/common/scalar.resolver.ts
  src/graphql/generated/graphql.ts
  src/graphql/generated/schema.graphql
  src/graphql/store/ORM.ts
  src/graphql/store/Object.graphql
  src/graphql/user/Mutation.graphql
  src/graphql/user/Mutation.resolver.ts
  src/graphql/user/ORM.ts
  src/graphql/user/Query.graphql
  src/graphql/user/Query.resolver.ts
  src/graphql/user/sql/byId.sql
  src/graphql/user/sql/joinFollower.sql
  src/graphql/user/sql/joinFollowing.sql
  src/graphql/user/sql/login.sql
  src/graphql/user/sql/register.sql
  src/utils/commons.ts
  yarn.lock
Labels: 🧪 test
